cmd: git add -A ; git commit -m "Auto Commit" -a ; git push origin master ; npm publish
targets:
  deployRPi:
    cmd: ssh root@192.168.192.54 "npm install -g casa-corrently-core-container@latest; pm2 restart casa-corrently"
  docker-build-push:
    cmd: "docker build -t stromdao/casa-corrently-container .;docker push stromdao/casa-corrently-container"
  docker-run:
    cmd: "docker run --name casa-corrently-container --net='host' -d stromdao/casa-corrently-container "
  docker-push:
    cmd: "docker push stromdao/casa-corrently-container"
  docker-create-service:
    cmd: "docker service create --name casa-corrently-container -p 8081:3000 --config casa-corrently-docker stromdao/casa-corrently-container"
  docker-rm-service:
    cmd: "docker service rm casa-corrently-container"
  demo-deploy-docker:
    cmd: "docker build -t stromdao/casa-corrently-container .; docker push stromdao/casa-corrently-container; ssh root@l2.stromdao.de /opt/casa-docker/restart_openems.sh; ssh root@pag.stromdao.de /opt/casa-corrently-docker/restart_openems.sh"
